encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Investment Screening" # Site name or title
logo: "/assets/logos/icon.png" # Site logo
description: "A research project showcasing interdisciplinary research on the impact of screening inward FDI for national security, combining insights from economics, political science, and law." # Site description and default description (meta-description)
url: "https://https://investmentscreening.github.io" # Site url, also used in jekyll-seo-tag
#baseurl: ""
repo: "https://https://github.com/investmentscreening/investmentscreening.github.io"
google_analytics: "G-FGRTYR2V1S"

sass:
    style: compressed

markdown: kramdown
highlighter: rouge

navigation:
  - title: Home
    url: /
  - title: Research
    url: /research
  - title: Our Team
    url: /our-team
#  - title: Data
#    url: /data
#  - title: Graphics
#    url: /graphics


footer: "[Investment Screening](https://investmentscreening.github.io/). ARC number: DP 200100639. UoM ethics approval number: 2021-22546-21613-3."

