remote_theme: daviddarnes/alembic@4.1.0

exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - alembic-jekyll-theme.gemspec
  - .jekyll-cache

# Set plugins
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji

paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page

encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "<Some economics website placeholder>" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "This is an economics website placeholder" # Site description and default description, also used in jekyll-seo-tag
url: "https://crstnn.github.io/jekyll-alembic-theme-poc" # Site url, also used in jekyll-seo-tag
#baseurl: ""
repo: "https://github.com/crstnn/jekyll-alembic-theme-poc"

sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)


navigation_header:
  - title: Home
    url: /